# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--indent=4"
          - "--no-sort-keys"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.0
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
      - id: ruff
        args: ["check", "--select", "I", "--fix"]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types: [python]
        args: [
            "-rn", # Only display messages
            "-sn", # Don't display the score
            "--disable=C0114,C0115,C0116,W1401,C0301", # Disable missing docstring and f-string warnings
          ]
      